### PR TITLE
Updated ical4j to `3.2.10`

### PR DESCRIPTION
**Pull request by ArnyminerZ**
~~Edit: Does not [fix](https://github.com/ical4j/ical4j/issues/454#issuecomment-1454972700) https://github.com/ical4j/ical4j/issues/454, does not fix https://github.com/bitfireAT/davx5/issues/165~~

### CODE REVIEW

**Comment by leonggs** [comment]
Recently, I've imported a third-party ics file to my Nextcloud calendar containing `SEQUENCE:2302221158`. It misuses the sequence field as booking date or something like that. All implementations such as ical4j that conform to the [iCalendar RFC standard](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.7.4) might fail parsing this encoding as 32 bit signed integers since 01.01.2022. Dear third-party, you have constructed a year2k, seriously? :D
- Nextcloud Calendar doesn't discard this standard-violating event, which I expect my calendar apps to do!
- Davx 4.3-ose does and displays an inconvenient error in the notification bar containing `net.fortuna.ical4j.data.ParserException` in its stack trace. For average users it's probably not possible to identify the problematic remote resource/event that causes that error.

Do the present fixes in the current issue fix my problem described above as well and will they be in the next release of Davx without further actions?

**Comment by rfc2822** [comment]
Shall we merge it although it does not fix the original problem?

**Comment by ArnyminerZ** [comment]
Mmmh... Maybe... It's always good to have dependencies updated, there might be other bugfixes

**Comment by rfc2822** [comment]
Agree…

There's a failing test though.

**Comment by rfc2822** [comment]
Ah, nice, seems that it fixes a Persian Locale bug. Please keep the test to be sure in the future and just remove the failure expecation :)

**Review by rfc2822 — APPROVED** [review]
👍🏻

**Pull request merged**
