### PR TITLE
jtx Board 2.3 with improved recur handling

### PR DESCRIPTION
**Pull request by patrickunterwegs**

### CODE REVIEW

**Comment by patrickunterwegs** [comment]
Hi @rfc2822 , we should make sure DAVx5 and jtx Board get released together for those changes!

**Comment by rfc2822** [comment]
> Hi @rfc2822 , we should make sure DAVx5 and jtx Board get released together for those changes!

Which DAVx⁵ version number/code did you finally set as minimum requirement in jtxBoard, 4.3.1? We could create issues in DAVx5 and jtxBoard and link them together (and assign the 4.3.1 milestone at least for the DAVx5 issue) to make sure we don't forget it.

**Review by rfc2822 — APPROVED** [review]

**Comment by patrickunterwegs** [comment]
> > Hi @rfc2822 , we should make sure DAVx5 and jtx Board get released together for those changes!
> 
> Which DAVx⁵ version number/code did you finally set as minimum requirement in jtxBoard, 4.3.1? We could create issues in DAVx5 and jtxBoard and link them together (and assign the 4.3.1 milestone at least for the DAVx5 issue) to make sure we don't forget it.

Yes, the check is for 4.3.1, so the app checks for version code 403010000. 
You mean to not forget what exactly?

**Comment by rfc2822** [comment]
> You mean to not forget what exactly?

Just that we have to release the version at the same time. Before releasing, we have a look at the [respective milestone](https://github.com/bitfireAT/davx5/milestone/16), so we are remembered then.

**Comment by patrickunterwegs** [comment]
For me it's okay just to agree on it now, I'd like to release a beta as soon as possible, maybe on Monday?

**Comment by rfc2822** [comment]
@devvv4ever @sunkup What do you think? We just had the 4.3 release, but we could do 4.3.1 soon with only this patch + the new DAV:owner detection. The latter one is almost ready I think, but we'd need some beta time.

**Comment by patrickunterwegs** [comment]
> @devvv4ever @sunkup What do you think? We just had the 4.3 release, but we could do 4.3.1 soon with only this patch + the new DAV:owner detection. The latter one is almost ready I think, but we'd need some beta time.

Sounds good 👍

**Comment by rfc2822** [comment]
Perfect, please follow up in bitfireAT/davx5#209

**Comment by devvv4ever** [comment]
Yes, I'm fine with shooting out 4.3.1 next week after some days of beta testing.

**Pull request merged**
