### PR TITLE
Handling period durations of days with `T` suffix

### LINKED ISSUE #77: Handling period durations of days with `T` prefix
There has been detected some instances where the ICS file has an invalid duration, for example this trigger:
```
TRIGGER:-P2DT
```
Trying to parse it in [Kotlin Playground](https://pl.kotl.in/W0YJNVg28) shows that is not a valid duration, which is what ICSx5 complains about when trying to load those kind of URLs.

The [Java Documentation](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-) is not very clear about the use of the `T` prefix. However, [this StackOverflow post](https://stackoverflow.com/a/51168078) doesn't mention `D` as a valid unit for periods with the `T` prefix, which this is the case. To be clearer:
```
TRIGGER:-PT2H    <- VALID
TRIGGER:-PT2D    <- INVALID
```

### PR DESCRIPTION
**Pull request by ArnyminerZ**
Closes #77

### CODE REVIEW

**Review by sunkup — APPROVED** [review]
Looking good :)

**Review by rfc2822 — APPROVED** [review]
Thanks :)

**Comment by devvv4ever** [comment]
@ArnyminerZ Didn't this fix make it to 2.1.1? The original URL is still unable to be parsed with the "Text cannot be parsed to a Duration" exception...

**Comment by ArnyminerZ** [comment]
@rfc2822 would tell better, but I think so

**Pull request merged**
